
package com.xiaohao.dubbodemo.consumer.webService;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.15
 * 2014-09-05T10:02:06.892+08:00
 * Generated source version: 2.6.15
 * 
 */
public final class IDubboWebServiceDemoServicePortType_IDubboWebServiceDemoServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.dubbodemo.xiaohao.com/", "IDubboWebServiceDemoService");

    private IDubboWebServiceDemoServicePortType_IDubboWebServiceDemoServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = IDubboWebServiceDemoService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        IDubboWebServiceDemoService ss = new IDubboWebServiceDemoService(wsdlURL, SERVICE_NAME);
        IDubboWebServiceDemoServicePortType port = ss.getIDubboWebServiceDemoServicePort();  
        
        {
        System.out.println("Invoking webServiceSayHello...");
        java.lang.String _webServiceSayHello_arg0 = "";
        java.lang.String _webServiceSayHello__return = port.webServiceSayHello(_webServiceSayHello_arg0);
        System.out.println("webServiceSayHello.result=" + _webServiceSayHello__return);


        }

        System.exit(0);
    }

}
