package com.xiaohao.dubbodemo.consumer.webService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.15
 * 2014-09-05T10:02:06.947+08:00
 * Generated source version: 2.6.15
 * 
 */
@WebServiceClient(name = "IDubboWebServiceDemoService", 
                  wsdlLocation = "file:/F:/myCode/dubbodemo/consumer/src/main/java/com/xiaohao/dubbodemo/consumer/webService/com.xiaohao.dubbodemo.service.IDubboWebServiceDemoService",
                  targetNamespace = "http://service.dubbodemo.xiaohao.com/") 
public class IDubboWebServiceDemoService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.dubbodemo.xiaohao.com/", "IDubboWebServiceDemoService");
    public final static QName IDubboWebServiceDemoServicePort = new QName("http://service.dubbodemo.xiaohao.com/", "IDubboWebServiceDemoServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/F:/myCode/dubbodemo/consumer/src/main/java/com/xiaohao/dubbodemo/consumer/webService/com.xiaohao.dubbodemo.service.IDubboWebServiceDemoService");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IDubboWebServiceDemoService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/F:/myCode/dubbodemo/consumer/src/main/java/com/xiaohao/dubbodemo/consumer/webService/com.xiaohao.dubbodemo.service.IDubboWebServiceDemoService");
        }
        WSDL_LOCATION = url;
    }

    public IDubboWebServiceDemoService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IDubboWebServiceDemoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IDubboWebServiceDemoService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns IDubboWebServiceDemoServicePortType
     */
    @WebEndpoint(name = "IDubboWebServiceDemoServicePort")
    public IDubboWebServiceDemoServicePortType getIDubboWebServiceDemoServicePort() {
        return super.getPort(IDubboWebServiceDemoServicePort, IDubboWebServiceDemoServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IDubboWebServiceDemoServicePortType
     */
    @WebEndpoint(name = "IDubboWebServiceDemoServicePort")
    public IDubboWebServiceDemoServicePortType getIDubboWebServiceDemoServicePort(WebServiceFeature... features) {
        return super.getPort(IDubboWebServiceDemoServicePort, IDubboWebServiceDemoServicePortType.class, features);
    }

}
